version: '3'

services:
  jq:
    image: stedolan/jq
    volumes:
      - ./:/go/src/github.com/cockroachdb/cockroach-cloud-sdk-go
    working_dir: /go/src/github.com/cockroachdb/cockroach-cloud-sdk-go

  openapi-generator:
    image: openapitools/openapi-generator-cli:v6.2.0
    volumes:
      - ./:/go/src/github.com/cockroachdb/cockroach-cloud-sdk-go
    working_dir: /go/src/github.com/cockroachdb/cockroach-cloud-sdk-go
