/*
CockroachDB Cloud API

No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)

API version: 2021-12-28
Contact: support@cockroachlabs.com
*/

// Code generated by OpenAPI Generator (https://openapi-generator.tech); DO NOT EDIT.

package openapi

import (
	"encoding/json"
)

// CreateSQLUserRequest struct for CreateSQLUserRequest
type CreateSQLUserRequest struct {
	User SQLUser `json:"user"`
	Password string `json:"password"`
}

// NewCreateSQLUserRequest instantiates a new CreateSQLUserRequest object
// This constructor will assign default values to properties that have it defined,
// and makes sure properties required by API are set, but the set of arguments
// will change when the set of required properties is changed
func NewCreateSQLUserRequest(user SQLUser, password string) *CreateSQLUserRequest {
	this := CreateSQLUserRequest{}
	this.User = user
	this.Password = password
	return &this
}

// NewCreateSQLUserRequestWithDefaults instantiates a new CreateSQLUserRequest object
// This constructor will only assign default values to properties that have it defined,
// but it doesn't guarantee that properties required by API are set
func NewCreateSQLUserRequestWithDefaults() *CreateSQLUserRequest {
	this := CreateSQLUserRequest{}
	return &this
}

// GetUser returns the User field value
func (o *CreateSQLUserRequest) GetUser() SQLUser {
	if o == nil {
		var ret SQLUser
		return ret
	}

	return o.User
}

// GetUserOk returns a tuple with the User field value
// and a boolean to check if the value has been set.
func (o *CreateSQLUserRequest) GetUserOk() (*SQLUser, bool) {
	if o == nil  {
		return nil, false
	}
	return &o.User, true
}

// SetUser sets field value
func (o *CreateSQLUserRequest) SetUser(v SQLUser) {
	o.User = v
}

// GetPassword returns the Password field value
func (o *CreateSQLUserRequest) GetPassword() string {
	if o == nil {
		var ret string
		return ret
	}

	return o.Password
}

// GetPasswordOk returns a tuple with the Password field value
// and a boolean to check if the value has been set.
func (o *CreateSQLUserRequest) GetPasswordOk() (*string, bool) {
	if o == nil  {
		return nil, false
	}
	return &o.Password, true
}

// SetPassword sets field value
func (o *CreateSQLUserRequest) SetPassword(v string) {
	o.Password = v
}

func (o CreateSQLUserRequest) MarshalJSON() ([]byte, error) {
	toSerialize := map[string]interface{}{}
	if true {
		toSerialize["user"] = o.User
	}
	if true {
		toSerialize["password"] = o.Password
	}
	return json.Marshal(toSerialize)
}

type NullableCreateSQLUserRequest struct {
	value *CreateSQLUserRequest
	isSet bool
}

func (v NullableCreateSQLUserRequest) Get() *CreateSQLUserRequest {
	return v.value
}

func (v *NullableCreateSQLUserRequest) Set(val *CreateSQLUserRequest) {
	v.value = val
	v.isSet = true
}

func (v NullableCreateSQLUserRequest) IsSet() bool {
	return v.isSet
}

func (v *NullableCreateSQLUserRequest) Unset() {
	v.value = nil
	v.isSet = false
}

func NewNullableCreateSQLUserRequest(val *CreateSQLUserRequest) *NullableCreateSQLUserRequest {
	return &NullableCreateSQLUserRequest{value: val, isSet: true}
}

func (v NullableCreateSQLUserRequest) MarshalJSON() ([]byte, error) {
	return json.Marshal(v.value)
}

func (v *NullableCreateSQLUserRequest) UnmarshalJSON(src []byte) error {
	v.isSet = true
	return json.Unmarshal(src, &v.value)
}


