/*
CockroachDB Cloud API

No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)

API version: 2021-12-28
Contact: support@cockroachlabs.com
*/

// Code generated by OpenAPI Generator (https://openapi-generator.tech); DO NOT EDIT.

package openapi

import (
	"encoding/json"
)

// DedicatedMachineTypeSpecification struct for DedicatedMachineTypeSpecification
type DedicatedMachineTypeSpecification struct {
	// MachineType is the machine type identifier within the given cloud provider, ex. m5.xlarge, n2-standard-4.
	MachineType *string `json:"machine_type,omitempty"`
	// NumVirtualCPUs may be used to automatically select a machine type according to the desired number of vCPUs.
	NumVirtualCpus *int32 `json:"num_virtual_cpus,omitempty"`
}

// NewDedicatedMachineTypeSpecification instantiates a new DedicatedMachineTypeSpecification object
// This constructor will assign default values to properties that have it defined,
// and makes sure properties required by API are set, but the set of arguments
// will change when the set of required properties is changed
func NewDedicatedMachineTypeSpecification() *DedicatedMachineTypeSpecification {
	this := DedicatedMachineTypeSpecification{}
	return &this
}

// NewDedicatedMachineTypeSpecificationWithDefaults instantiates a new DedicatedMachineTypeSpecification object
// This constructor will only assign default values to properties that have it defined,
// but it doesn't guarantee that properties required by API are set
func NewDedicatedMachineTypeSpecificationWithDefaults() *DedicatedMachineTypeSpecification {
	this := DedicatedMachineTypeSpecification{}
	return &this
}

// GetMachineType returns the MachineType field value if set, zero value otherwise.
func (o *DedicatedMachineTypeSpecification) GetMachineType() string {
	if o == nil || o.MachineType == nil {
		var ret string
		return ret
	}
	return *o.MachineType
}

// GetMachineTypeOk returns a tuple with the MachineType field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *DedicatedMachineTypeSpecification) GetMachineTypeOk() (*string, bool) {
	if o == nil || o.MachineType == nil {
		return nil, false
	}
	return o.MachineType, true
}

// HasMachineType returns a boolean if a field has been set.
func (o *DedicatedMachineTypeSpecification) HasMachineType() bool {
	if o != nil && o.MachineType != nil {
		return true
	}

	return false
}

// SetMachineType gets a reference to the given string and assigns it to the MachineType field.
func (o *DedicatedMachineTypeSpecification) SetMachineType(v string) {
	o.MachineType = &v
}

// GetNumVirtualCpus returns the NumVirtualCpus field value if set, zero value otherwise.
func (o *DedicatedMachineTypeSpecification) GetNumVirtualCpus() int32 {
	if o == nil || o.NumVirtualCpus == nil {
		var ret int32
		return ret
	}
	return *o.NumVirtualCpus
}

// GetNumVirtualCpusOk returns a tuple with the NumVirtualCpus field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *DedicatedMachineTypeSpecification) GetNumVirtualCpusOk() (*int32, bool) {
	if o == nil || o.NumVirtualCpus == nil {
		return nil, false
	}
	return o.NumVirtualCpus, true
}

// HasNumVirtualCpus returns a boolean if a field has been set.
func (o *DedicatedMachineTypeSpecification) HasNumVirtualCpus() bool {
	if o != nil && o.NumVirtualCpus != nil {
		return true
	}

	return false
}

// SetNumVirtualCpus gets a reference to the given int32 and assigns it to the NumVirtualCpus field.
func (o *DedicatedMachineTypeSpecification) SetNumVirtualCpus(v int32) {
	o.NumVirtualCpus = &v
}

func (o DedicatedMachineTypeSpecification) MarshalJSON() ([]byte, error) {
	toSerialize := map[string]interface{}{}
	if o.MachineType != nil {
		toSerialize["machine_type"] = o.MachineType
	}
	if o.NumVirtualCpus != nil {
		toSerialize["num_virtual_cpus"] = o.NumVirtualCpus
	}
	return json.Marshal(toSerialize)
}

type NullableDedicatedMachineTypeSpecification struct {
	value *DedicatedMachineTypeSpecification
	isSet bool
}

func (v NullableDedicatedMachineTypeSpecification) Get() *DedicatedMachineTypeSpecification {
	return v.value
}

func (v *NullableDedicatedMachineTypeSpecification) Set(val *DedicatedMachineTypeSpecification) {
	v.value = val
	v.isSet = true
}

func (v NullableDedicatedMachineTypeSpecification) IsSet() bool {
	return v.isSet
}

func (v *NullableDedicatedMachineTypeSpecification) Unset() {
	v.value = nil
	v.isSet = false
}

func NewNullableDedicatedMachineTypeSpecification(val *DedicatedMachineTypeSpecification) *NullableDedicatedMachineTypeSpecification {
	return &NullableDedicatedMachineTypeSpecification{value: val, isSet: true}
}

func (v NullableDedicatedMachineTypeSpecification) MarshalJSON() ([]byte, error) {
	return json.Marshal(v.value)
}

func (v *NullableDedicatedMachineTypeSpecification) UnmarshalJSON(src []byte) error {
	v.isSet = true
	return json.Unmarshal(src, &v.value)
}


