/*
CockroachDB Cloud API

No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)

API version: 2021-12-28
Contact: support@cockroachlabs.com
*/

// Code generated by OpenAPI Generator (https://openapi-generator.tech); DO NOT EDIT.

package openapi

import (
	"encoding/json"
)

// SQLUser struct for SQLUser
type SQLUser struct {
	Name string `json:"name"`
}

// NewSQLUser instantiates a new SQLUser object
// This constructor will assign default values to properties that have it defined,
// and makes sure properties required by API are set, but the set of arguments
// will change when the set of required properties is changed
func NewSQLUser(name string) *SQLUser {
	this := SQLUser{}
	this.Name = name
	return &this
}

// NewSQLUserWithDefaults instantiates a new SQLUser object
// This constructor will only assign default values to properties that have it defined,
// but it doesn't guarantee that properties required by API are set
func NewSQLUserWithDefaults() *SQLUser {
	this := SQLUser{}
	return &this
}

// GetName returns the Name field value
func (o *SQLUser) GetName() string {
	if o == nil {
		var ret string
		return ret
	}

	return o.Name
}

// GetNameOk returns a tuple with the Name field value
// and a boolean to check if the value has been set.
func (o *SQLUser) GetNameOk() (*string, bool) {
	if o == nil  {
		return nil, false
	}
	return &o.Name, true
}

// SetName sets field value
func (o *SQLUser) SetName(v string) {
	o.Name = v
}

func (o SQLUser) MarshalJSON() ([]byte, error) {
	toSerialize := map[string]interface{}{}
	if true {
		toSerialize["name"] = o.Name
	}
	return json.Marshal(toSerialize)
}

type NullableSQLUser struct {
	value *SQLUser
	isSet bool
}

func (v NullableSQLUser) Get() *SQLUser {
	return v.value
}

func (v *NullableSQLUser) Set(val *SQLUser) {
	v.value = val
	v.isSet = true
}

func (v NullableSQLUser) IsSet() bool {
	return v.isSet
}

func (v *NullableSQLUser) Unset() {
	v.value = nil
	v.isSet = false
}

func NewNullableSQLUser(val *SQLUser) *NullableSQLUser {
	return &NullableSQLUser{value: val, isSet: true}
}

func (v NullableSQLUser) MarshalJSON() ([]byte, error) {
	return json.Marshal(v.value)
}

func (v *NullableSQLUser) UnmarshalJSON(src []byte) error {
	v.isSet = true
	return json.Unmarshal(src, &v.value)
}


