/*
CockroachDB Cloud API

No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)

API version: 2021-12-28
Contact: support@cockroachlabs.com
*/

// Code generated by OpenAPI Generator (https://openapi-generator.tech); DO NOT EDIT.

package openapi

import (
	"encoding/json"
)

// UpdateCMEKStatusRequest struct for UpdateCMEKStatusRequest
type UpdateCMEKStatusRequest struct {
	Action CMEKCustomerAction `json:"action"`
}

// NewUpdateCMEKStatusRequest instantiates a new UpdateCMEKStatusRequest object
// This constructor will assign default values to properties that have it defined,
// and makes sure properties required by API are set, but the set of arguments
// will change when the set of required properties is changed
func NewUpdateCMEKStatusRequest(action CMEKCustomerAction) *UpdateCMEKStatusRequest {
	this := UpdateCMEKStatusRequest{}
	this.Action = action
	return &this
}

// NewUpdateCMEKStatusRequestWithDefaults instantiates a new UpdateCMEKStatusRequest object
// This constructor will only assign default values to properties that have it defined,
// but it doesn't guarantee that properties required by API are set
func NewUpdateCMEKStatusRequestWithDefaults() *UpdateCMEKStatusRequest {
	this := UpdateCMEKStatusRequest{}
	var action CMEKCustomerAction = UNKNOWN_ACTION
	this.Action = action
	return &this
}

// GetAction returns the Action field value
func (o *UpdateCMEKStatusRequest) GetAction() CMEKCustomerAction {
	if o == nil {
		var ret CMEKCustomerAction
		return ret
	}

	return o.Action
}

// GetActionOk returns a tuple with the Action field value
// and a boolean to check if the value has been set.
func (o *UpdateCMEKStatusRequest) GetActionOk() (*CMEKCustomerAction, bool) {
	if o == nil  {
		return nil, false
	}
	return &o.Action, true
}

// SetAction sets field value
func (o *UpdateCMEKStatusRequest) SetAction(v CMEKCustomerAction) {
	o.Action = v
}

func (o UpdateCMEKStatusRequest) MarshalJSON() ([]byte, error) {
	toSerialize := map[string]interface{}{}
	if true {
		toSerialize["action"] = o.Action
	}
	return json.Marshal(toSerialize)
}

type NullableUpdateCMEKStatusRequest struct {
	value *UpdateCMEKStatusRequest
	isSet bool
}

func (v NullableUpdateCMEKStatusRequest) Get() *UpdateCMEKStatusRequest {
	return v.value
}

func (v *NullableUpdateCMEKStatusRequest) Set(val *UpdateCMEKStatusRequest) {
	v.value = val
	v.isSet = true
}

func (v NullableUpdateCMEKStatusRequest) IsSet() bool {
	return v.isSet
}

func (v *NullableUpdateCMEKStatusRequest) Unset() {
	v.value = nil
	v.isSet = false
}

func NewNullableUpdateCMEKStatusRequest(val *UpdateCMEKStatusRequest) *NullableUpdateCMEKStatusRequest {
	return &NullableUpdateCMEKStatusRequest{value: val, isSet: true}
}

func (v NullableUpdateCMEKStatusRequest) MarshalJSON() ([]byte, error) {
	return json.Marshal(v.value)
}

func (v *NullableUpdateCMEKStatusRequest) UnmarshalJSON(src []byte) error {
	v.isSet = true
	return json.Unmarshal(src, &v.value)
}


