/*
CockroachDB Cloud API

No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)

API version: 2021-12-28
Contact: support@cockroachlabs.com
*/

// Code generated by OpenAPI Generator (https://openapi-generator.tech); DO NOT EDIT.

package openapi

import (
	"encoding/json"
)

// DedicatedHardwareUpdateSpecification struct for DedicatedHardwareUpdateSpecification
type DedicatedHardwareUpdateSpecification struct {
	MachineSpec *DedicatedMachineTypeSpecification `json:"machine_spec,omitempty"`
	// StorageGiB is the number of storage GiB per node in the cluster.
	StorageGib *int32 `json:"storage_gib,omitempty"`
	// DiskIOPs is the number of disk I/O operations per second that are permitted on each node in the cluster. Zero indicates the cloud provider-specific default. Only available for AWS clusters.
	DiskIops *int32 `json:"disk_iops,omitempty"`
}

// NewDedicatedHardwareUpdateSpecification instantiates a new DedicatedHardwareUpdateSpecification object
// This constructor will assign default values to properties that have it defined,
// and makes sure properties required by API are set, but the set of arguments
// will change when the set of required properties is changed
func NewDedicatedHardwareUpdateSpecification() *DedicatedHardwareUpdateSpecification {
	this := DedicatedHardwareUpdateSpecification{}
	return &this
}

// NewDedicatedHardwareUpdateSpecificationWithDefaults instantiates a new DedicatedHardwareUpdateSpecification object
// This constructor will only assign default values to properties that have it defined,
// but it doesn't guarantee that properties required by API are set
func NewDedicatedHardwareUpdateSpecificationWithDefaults() *DedicatedHardwareUpdateSpecification {
	this := DedicatedHardwareUpdateSpecification{}
	return &this
}

// GetMachineSpec returns the MachineSpec field value if set, zero value otherwise.
func (o *DedicatedHardwareUpdateSpecification) GetMachineSpec() DedicatedMachineTypeSpecification {
	if o == nil || o.MachineSpec == nil {
		var ret DedicatedMachineTypeSpecification
		return ret
	}
	return *o.MachineSpec
}

// GetMachineSpecOk returns a tuple with the MachineSpec field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *DedicatedHardwareUpdateSpecification) GetMachineSpecOk() (*DedicatedMachineTypeSpecification, bool) {
	if o == nil || o.MachineSpec == nil {
		return nil, false
	}
	return o.MachineSpec, true
}

// HasMachineSpec returns a boolean if a field has been set.
func (o *DedicatedHardwareUpdateSpecification) HasMachineSpec() bool {
	if o != nil && o.MachineSpec != nil {
		return true
	}

	return false
}

// SetMachineSpec gets a reference to the given DedicatedMachineTypeSpecification and assigns it to the MachineSpec field.
func (o *DedicatedHardwareUpdateSpecification) SetMachineSpec(v DedicatedMachineTypeSpecification) {
	o.MachineSpec = &v
}

// GetStorageGib returns the StorageGib field value if set, zero value otherwise.
func (o *DedicatedHardwareUpdateSpecification) GetStorageGib() int32 {
	if o == nil || o.StorageGib == nil {
		var ret int32
		return ret
	}
	return *o.StorageGib
}

// GetStorageGibOk returns a tuple with the StorageGib field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *DedicatedHardwareUpdateSpecification) GetStorageGibOk() (*int32, bool) {
	if o == nil || o.StorageGib == nil {
		return nil, false
	}
	return o.StorageGib, true
}

// HasStorageGib returns a boolean if a field has been set.
func (o *DedicatedHardwareUpdateSpecification) HasStorageGib() bool {
	if o != nil && o.StorageGib != nil {
		return true
	}

	return false
}

// SetStorageGib gets a reference to the given int32 and assigns it to the StorageGib field.
func (o *DedicatedHardwareUpdateSpecification) SetStorageGib(v int32) {
	o.StorageGib = &v
}

// GetDiskIops returns the DiskIops field value if set, zero value otherwise.
func (o *DedicatedHardwareUpdateSpecification) GetDiskIops() int32 {
	if o == nil || o.DiskIops == nil {
		var ret int32
		return ret
	}
	return *o.DiskIops
}

// GetDiskIopsOk returns a tuple with the DiskIops field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *DedicatedHardwareUpdateSpecification) GetDiskIopsOk() (*int32, bool) {
	if o == nil || o.DiskIops == nil {
		return nil, false
	}
	return o.DiskIops, true
}

// HasDiskIops returns a boolean if a field has been set.
func (o *DedicatedHardwareUpdateSpecification) HasDiskIops() bool {
	if o != nil && o.DiskIops != nil {
		return true
	}

	return false
}

// SetDiskIops gets a reference to the given int32 and assigns it to the DiskIops field.
func (o *DedicatedHardwareUpdateSpecification) SetDiskIops(v int32) {
	o.DiskIops = &v
}

func (o DedicatedHardwareUpdateSpecification) MarshalJSON() ([]byte, error) {
	toSerialize := map[string]interface{}{}
	if o.MachineSpec != nil {
		toSerialize["machine_spec"] = o.MachineSpec
	}
	if o.StorageGib != nil {
		toSerialize["storage_gib"] = o.StorageGib
	}
	if o.DiskIops != nil {
		toSerialize["disk_iops"] = o.DiskIops
	}
	return json.Marshal(toSerialize)
}

type NullableDedicatedHardwareUpdateSpecification struct {
	value *DedicatedHardwareUpdateSpecification
	isSet bool
}

func (v NullableDedicatedHardwareUpdateSpecification) Get() *DedicatedHardwareUpdateSpecification {
	return v.value
}

func (v *NullableDedicatedHardwareUpdateSpecification) Set(val *DedicatedHardwareUpdateSpecification) {
	v.value = val
	v.isSet = true
}

func (v NullableDedicatedHardwareUpdateSpecification) IsSet() bool {
	return v.isSet
}

func (v *NullableDedicatedHardwareUpdateSpecification) Unset() {
	v.value = nil
	v.isSet = false
}

func NewNullableDedicatedHardwareUpdateSpecification(val *DedicatedHardwareUpdateSpecification) *NullableDedicatedHardwareUpdateSpecification {
	return &NullableDedicatedHardwareUpdateSpecification{value: val, isSet: true}
}

func (v NullableDedicatedHardwareUpdateSpecification) MarshalJSON() ([]byte, error) {
	return json.Marshal(v.value)
}

func (v *NullableDedicatedHardwareUpdateSpecification) UnmarshalJSON(src []byte) error {
	v.isSet = true
	return json.Unmarshal(src, &v.value)
}


