/*
CockroachDB Cloud API

No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)

API version: 2021-12-28
Contact: support@cockroachlabs.com
*/

// Code generated by OpenAPI Generator (https://openapi-generator.tech); DO NOT EDIT.

package openapi

import (
	"encoding/json"
	"fmt"
)

// CloudProvider  - CLOUD_PROVIDER_GCP: The Google Cloud Platform cloud provider.  - CLOUD_PROVIDER_AWS: The Amazon Web Services cloud provider.
type CloudProvider string

// List of CloudProvider
const (
	UNSPECIFIED CloudProvider = "CLOUD_PROVIDER_UNSPECIFIED"
	GCP CloudProvider = "CLOUD_PROVIDER_GCP"
	AWS CloudProvider = "CLOUD_PROVIDER_AWS"
)

// All allowed values of CloudProvider enum
var AllowedCloudProviderEnumValues = []CloudProvider{
	"CLOUD_PROVIDER_UNSPECIFIED",
	"CLOUD_PROVIDER_GCP",
	"CLOUD_PROVIDER_AWS",
}

func (v *CloudProvider) UnmarshalJSON(src []byte) error {
	var value string
	err := json.Unmarshal(src, &value)
	if err != nil {
		return err
	}
	enumTypeValue := CloudProvider(value)
	for _, existing := range AllowedCloudProviderEnumValues {
		if existing == enumTypeValue {
			*v = enumTypeValue
			return nil
		}
	}

	return fmt.Errorf("%+v is not a valid CloudProvider", value)
}

// NewCloudProviderFromValue returns a pointer to a valid CloudProvider
// for the value passed as argument, or an error if the value passed is not allowed by the enum
func NewCloudProviderFromValue(v string) (*CloudProvider, error) {
	ev := CloudProvider(v)
	if ev.IsValid() {
		return &ev, nil
	} else {
		return nil, fmt.Errorf("invalid value '%v' for CloudProvider: valid values are %v", v, AllowedCloudProviderEnumValues)
	}
}

// IsValid return true if the value is valid for the enum, false otherwise
func (v CloudProvider) IsValid() bool {
	for _, existing := range AllowedCloudProviderEnumValues {
		if existing == v {
			return true
		}
	}
	return false
}

// Ptr returns reference to CloudProvider value
func (v CloudProvider) Ptr() *CloudProvider {
	return &v
}

type NullableCloudProvider struct {
	value *CloudProvider
	isSet bool
}

func (v NullableCloudProvider) Get() *CloudProvider {
	return v.value
}

func (v *NullableCloudProvider) Set(val *CloudProvider) {
	v.value = val
	v.isSet = true
}

func (v NullableCloudProvider) IsSet() bool {
	return v.isSet
}

func (v *NullableCloudProvider) Unset() {
	v.value = nil
	v.isSet = false
}

func NewNullableCloudProvider(val *CloudProvider) *NullableCloudProvider {
	return &NullableCloudProvider{value: val, isSet: true}
}

func (v NullableCloudProvider) MarshalJSON() ([]byte, error) {
	return json.Marshal(v.value)
}

func (v *NullableCloudProvider) UnmarshalJSON(src []byte) error {
	v.isSet = true
	return json.Unmarshal(src, &v.value)
}

