/*
CockroachDB Cloud API

No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)

API version: 2021-12-28
Contact: support@cockroachlabs.com
*/

// Code generated by OpenAPI Generator (https://openapi-generator.tech); DO NOT EDIT.

package openapi

import (
	"encoding/json"
)

// CreateClusterSpecification struct for CreateClusterSpecification
type CreateClusterSpecification struct {
	Dedicated *DedicatedClusterCreateSpecification `json:"dedicated,omitempty"`
	Serverless *ServerlessClusterSpecification `json:"serverless,omitempty"`
}

// NewCreateClusterSpecification instantiates a new CreateClusterSpecification object
// This constructor will assign default values to properties that have it defined,
// and makes sure properties required by API are set, but the set of arguments
// will change when the set of required properties is changed
func NewCreateClusterSpecification() *CreateClusterSpecification {
	this := CreateClusterSpecification{}
	return &this
}

// NewCreateClusterSpecificationWithDefaults instantiates a new CreateClusterSpecification object
// This constructor will only assign default values to properties that have it defined,
// but it doesn't guarantee that properties required by API are set
func NewCreateClusterSpecificationWithDefaults() *CreateClusterSpecification {
	this := CreateClusterSpecification{}
	return &this
}

// GetDedicated returns the Dedicated field value if set, zero value otherwise.
func (o *CreateClusterSpecification) GetDedicated() DedicatedClusterCreateSpecification {
	if o == nil || o.Dedicated == nil {
		var ret DedicatedClusterCreateSpecification
		return ret
	}
	return *o.Dedicated
}

// GetDedicatedOk returns a tuple with the Dedicated field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *CreateClusterSpecification) GetDedicatedOk() (*DedicatedClusterCreateSpecification, bool) {
	if o == nil || o.Dedicated == nil {
		return nil, false
	}
	return o.Dedicated, true
}

// HasDedicated returns a boolean if a field has been set.
func (o *CreateClusterSpecification) HasDedicated() bool {
	if o != nil && o.Dedicated != nil {
		return true
	}

	return false
}

// SetDedicated gets a reference to the given DedicatedClusterCreateSpecification and assigns it to the Dedicated field.
func (o *CreateClusterSpecification) SetDedicated(v DedicatedClusterCreateSpecification) {
	o.Dedicated = &v
}

// GetServerless returns the Serverless field value if set, zero value otherwise.
func (o *CreateClusterSpecification) GetServerless() ServerlessClusterSpecification {
	if o == nil || o.Serverless == nil {
		var ret ServerlessClusterSpecification
		return ret
	}
	return *o.Serverless
}

// GetServerlessOk returns a tuple with the Serverless field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *CreateClusterSpecification) GetServerlessOk() (*ServerlessClusterSpecification, bool) {
	if o == nil || o.Serverless == nil {
		return nil, false
	}
	return o.Serverless, true
}

// HasServerless returns a boolean if a field has been set.
func (o *CreateClusterSpecification) HasServerless() bool {
	if o != nil && o.Serverless != nil {
		return true
	}

	return false
}

// SetServerless gets a reference to the given ServerlessClusterSpecification and assigns it to the Serverless field.
func (o *CreateClusterSpecification) SetServerless(v ServerlessClusterSpecification) {
	o.Serverless = &v
}

func (o CreateClusterSpecification) MarshalJSON() ([]byte, error) {
	toSerialize := map[string]interface{}{}
	if o.Dedicated != nil {
		toSerialize["dedicated"] = o.Dedicated
	}
	if o.Serverless != nil {
		toSerialize["serverless"] = o.Serverless
	}
	return json.Marshal(toSerialize)
}

type NullableCreateClusterSpecification struct {
	value *CreateClusterSpecification
	isSet bool
}

func (v NullableCreateClusterSpecification) Get() *CreateClusterSpecification {
	return v.value
}

func (v *NullableCreateClusterSpecification) Set(val *CreateClusterSpecification) {
	v.value = val
	v.isSet = true
}

func (v NullableCreateClusterSpecification) IsSet() bool {
	return v.isSet
}

func (v *NullableCreateClusterSpecification) Unset() {
	v.value = nil
	v.isSet = false
}

func NewNullableCreateClusterSpecification(val *CreateClusterSpecification) *NullableCreateClusterSpecification {
	return &NullableCreateClusterSpecification{value: val, isSet: true}
}

func (v NullableCreateClusterSpecification) MarshalJSON() ([]byte, error) {
	return json.Marshal(v.value)
}

func (v *NullableCreateClusterSpecification) UnmarshalJSON(src []byte) error {
	v.isSet = true
	return json.Unmarshal(src, &v.value)
}


