templateDir: internal/spec/templates
packageVersion: 6.0.0
# Include new templates and filenames.
files:
    service.mustache:
      templateType: SupportingFiles
      destinationFilename: service.go
    api.mustache:
      templateType: API
      destinationFilename: _ignore.txt
# Go generator options
# https://openapi-generator.tech/docs/generators/go
packageName: "client"
prependFormOrBodyParameters: false
structPrefix: false
# Generic generate options
# https://openapi-generator.tech/docs/usage#generate
removeOperationIdPrefix: true
# The 'additionalProperties' implementation is compliant with the OAS and JSON schema specifications.
disallowAdditionalPropertiesIfNotPresent: true 

# Prefix enum with class name
enumClassPrefix: true
