// Copyright 2022 The Cockroach Authors
//
// Licensed under the Apache License, Version 2.0 (the "License");
// you may not use this file except in compliance with the License.
// You may obtain a copy of the License at
//
// 	http://www.apache.org/licenses/LICENSE-2.0
//
// Unless required by applicable law or agreed to in writing, software
// distributed under the License is distributed on an "AS IS" BASIS,
// WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
// See the License for the specific language governing permissions and
// limitations under the License.

// Code generated by OpenAPI Generator (https://openapi-generator.tech); DO NOT EDIT.
// CockroachDB Cloud API
// API version: 2022-09-20

package client

import (
	"encoding/json"
)

// UserRoleGrants struct for UserRoleGrants.
type UserRoleGrants struct {
	Roles  *[]BuiltInRole `json:"roles,omitempty"`
	UserId *string        `json:"user_id,omitempty"`
}

// NewUserRoleGrants instantiates a new UserRoleGrants object.
// This constructor will assign default values to properties that have it defined,
// and makes sure properties required by API are set, but the set of arguments
// will change when the set of required properties is changed
func NewUserRoleGrants() *UserRoleGrants {
	p := UserRoleGrants{}
	return &p
}

// GetRoles returns the Roles field value if set, zero value otherwise.
func (o *UserRoleGrants) GetRoles() []BuiltInRole {
	if o == nil || o.Roles == nil {
		var ret []BuiltInRole
		return ret
	}
	return *o.Roles
}

// SetRoles gets a reference to the given []BuiltInRole and assigns it to the Roles field.
func (o *UserRoleGrants) SetRoles(v []BuiltInRole) {
	o.Roles = &v
}

// GetUserId returns the UserId field value if set, zero value otherwise.
func (o *UserRoleGrants) GetUserId() string {
	if o == nil || o.UserId == nil {
		var ret string
		return ret
	}
	return *o.UserId
}

// SetUserId gets a reference to the given string and assigns it to the UserId field.
func (o *UserRoleGrants) SetUserId(v string) {
	o.UserId = &v
}

func (o UserRoleGrants) MarshalJSON() ([]byte, error) {
	toSerialize := map[string]interface{}{}
	if o.Roles != nil {
		toSerialize["roles"] = o.Roles
	}
	if o.UserId != nil {
		toSerialize["user_id"] = o.UserId
	}
	return json.Marshal(toSerialize)
}
