// Code generated by OpenAPI Generator (https://openapi-generator.tech); DO NOT EDIT.
// CockroachDB Cloud API
// API version: 2022-07-12T00:00:00.000Z

package client

import (
	"encoding/json"
	"fmt"
)

// QuantityUnitType Billing QuantityUnitType is the unit type for a quantity of billing line item.
type QuantityUnitType string

// List of QuantityUnitType.
const (
	QUANTITYUNITTYPE_HOURS         QuantityUnitType = "HOURS"
	QUANTITYUNITTYPE_REQUEST_UNITS QuantityUnitType = "REQUEST_UNITS"
)

// All allowed values of QuantityUnitType enum.
var AllowedQuantityUnitTypeEnumValues = []QuantityUnitType{
	"HOURS",
	"REQUEST_UNITS",
}

func (v *QuantityUnitType) UnmarshalJSON(src []byte) error {
	var value string
	err := json.Unmarshal(src, &value)
	if err != nil {
		return err
	}
	enumTypeValue := QuantityUnitType(value)
	for _, existing := range AllowedQuantityUnitTypeEnumValues {
		if existing == enumTypeValue {
			*v = enumTypeValue
			return nil
		}
	}

	return fmt.Errorf("%+v is not a valid QuantityUnitType", value)
}

// NewQuantityUnitTypeFromValue returns a pointer to a valid QuantityUnitType
// for the value passed as argument, or an error if the value passed is not allowed by the enum.
func NewQuantityUnitTypeFromValue(v string) (*QuantityUnitType, error) {
	ev := QuantityUnitType(v)
	if ev.IsValid() {
		return &ev, nil
	} else {
		return nil, fmt.Errorf("invalid value '%v' for QuantityUnitType: valid values are %v", v, AllowedQuantityUnitTypeEnumValues)
	}
}

// IsValid return true if the value is valid for the enum, false otherwise.
func (v QuantityUnitType) IsValid() bool {
	for _, existing := range AllowedQuantityUnitTypeEnumValues {
		if existing == v {
			return true
		}
	}
	return false
}

// Ptr returns reference to QuantityUnitType value.
func (v QuantityUnitType) Ptr() *QuantityUnitType {
	return &v
}
