// Copyright 2022 The Cockroach Authors
//
// Licensed under the Apache License, Version 2.0 (the "License");
// you may not use this file except in compliance with the License.
// You may obtain a copy of the License at
//
// 	http://www.apache.org/licenses/LICENSE-2.0
//
// Unless required by applicable law or agreed to in writing, software
// distributed under the License is distributed on an "AS IS" BASIS,
// WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
// See the License for the specific language governing permissions and
// limitations under the License.

// Code generated by OpenAPI Generator (https://openapi-generator.tech); DO NOT EDIT.
// CockroachDB Cloud API
// API version: 2022-09-20

package client

import (
	"encoding/json"
)

// CockroachCloudSetAwsEndpointConnectionStateRequest struct for CockroachCloudSetAwsEndpointConnectionStateRequest.
type CockroachCloudSetAwsEndpointConnectionStateRequest struct {
	Status               *AWSEndpointConnectionStatus `json:"status,omitempty"`
	AdditionalProperties map[string]interface{}
}

type cockroachCloudSetAwsEndpointConnectionStateRequest CockroachCloudSetAwsEndpointConnectionStateRequest

// NewCockroachCloudSetAwsEndpointConnectionStateRequest instantiates a new CockroachCloudSetAwsEndpointConnectionStateRequest object.
// This constructor will assign default values to properties that have it defined,
// and makes sure properties required by API are set, but the set of arguments
// will change when the set of required properties is changed
func NewCockroachCloudSetAwsEndpointConnectionStateRequest() *CockroachCloudSetAwsEndpointConnectionStateRequest {
	p := CockroachCloudSetAwsEndpointConnectionStateRequest{}
	return &p
}

// GetStatus returns the Status field value if set, zero value otherwise.
func (o *CockroachCloudSetAwsEndpointConnectionStateRequest) GetStatus() AWSEndpointConnectionStatus {
	if o == nil || o.Status == nil {
		var ret AWSEndpointConnectionStatus
		return ret
	}
	return *o.Status
}

// SetStatus gets a reference to the given AWSEndpointConnectionStatus and assigns it to the Status field.
func (o *CockroachCloudSetAwsEndpointConnectionStateRequest) SetStatus(v AWSEndpointConnectionStatus) {
	o.Status = &v
}

func (o CockroachCloudSetAwsEndpointConnectionStateRequest) MarshalJSON() ([]byte, error) {
	toSerialize := map[string]interface{}{}
	if o.Status != nil {
		toSerialize["status"] = o.Status
	}

	for key, value := range o.AdditionalProperties {
		toSerialize[key] = value
	}

	return json.Marshal(toSerialize)
}

func (o *CockroachCloudSetAwsEndpointConnectionStateRequest) UnmarshalJSON(bytes []byte) (err error) {
	varCockroachCloudSetAwsEndpointConnectionStateRequest := cockroachCloudSetAwsEndpointConnectionStateRequest{}

	if err = json.Unmarshal(bytes, &varCockroachCloudSetAwsEndpointConnectionStateRequest); err == nil {
		*o = CockroachCloudSetAwsEndpointConnectionStateRequest(varCockroachCloudSetAwsEndpointConnectionStateRequest)
	}

	additionalProperties := make(map[string]interface{})

	if err = json.Unmarshal(bytes, &additionalProperties); err == nil {
		delete(additionalProperties, "status")
		o.AdditionalProperties = additionalProperties
	}

	return err
}
