// Copyright 2022 The Cockroach Authors
//
// Licensed under the Apache License, Version 2.0 (the "License");
// you may not use this file except in compliance with the License.
// You may obtain a copy of the License at
//
// 	http://www.apache.org/licenses/LICENSE-2.0
//
// Unless required by applicable law or agreed to in writing, software
// distributed under the License is distributed on an "AS IS" BASIS,
// WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
// See the License for the specific language governing permissions and
// limitations under the License.

// Code generated by OpenAPI Generator (https://openapi-generator.tech); DO NOT EDIT.
// CockroachDB Cloud API
// API version: 2022-03-31

package client

import (
	"encoding/json"
)

// SQLUser struct for SQLUser.
type SQLUser struct {
	Name                 string `json:"name"`
	AdditionalProperties map[string]interface{}
}

type sQLUser SQLUser

// NewSQLUser instantiates a new SQLUser object.
// This constructor will assign default values to properties that have it defined,
// and makes sure properties required by API are set, but the set of arguments
// will change when the set of required properties is changed
func NewSQLUser(name string) *SQLUser {
	p := SQLUser{}
	p.Name = name
	return &p
}

// NewSQLUserWithDefaults instantiates a new SQLUser object.
// This constructor will only assign default values to properties that have it defined,
// but it doesn't guarantee that properties required by API are set
func NewSQLUserWithDefaults() *SQLUser {
	p := SQLUser{}
	return &p
}

// GetName returns the Name field value.
func (o *SQLUser) GetName() string {
	if o == nil {
		var ret string
		return ret
	}

	return o.Name
}

// SetName sets field value.
func (o *SQLUser) SetName(v string) {
	o.Name = v
}

func (o SQLUser) MarshalJSON() ([]byte, error) {
	toSerialize := map[string]interface{}{}
	if true {
		toSerialize["name"] = o.Name
	}

	for key, value := range o.AdditionalProperties {
		toSerialize[key] = value
	}

	return json.Marshal(toSerialize)
}

func (o *SQLUser) UnmarshalJSON(bytes []byte) (err error) {
	varSQLUser := sQLUser{}

	if err = json.Unmarshal(bytes, &varSQLUser); err == nil {
		*o = SQLUser(varSQLUser)
	}

	additionalProperties := make(map[string]interface{})

	if err = json.Unmarshal(bytes, &additionalProperties); err == nil {
		delete(additionalProperties, "name")
		o.AdditionalProperties = additionalProperties
	}

	return err
}
