// Copyright 2022 The Cockroach Authors
//
// Licensed under the Apache License, Version 2.0 (the "License");
// you may not use this file except in compliance with the License.
// You may obtain a copy of the License at
//
// 	http://www.apache.org/licenses/LICENSE-2.0
//
// Unless required by applicable law or agreed to in writing, software
// distributed under the License is distributed on an "AS IS" BASIS,
// WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
// See the License for the specific language governing permissions and
// limitations under the License.

// Code generated by OpenAPI Generator (https://openapi-generator.tech); DO NOT EDIT.
// CockroachDB Cloud API
// API version: 2022-09-20

package client

import (
	"encoding/json"
	"fmt"
)

// MetricExportIntegrationType the model 'MetricExportIntegrationType'.
type MetricExportIntegrationType string

// List of MetricExportIntegrationType.
const (
	METRICEXPORTINTEGRATIONTYPE_DATADOG    MetricExportIntegrationType = "DATADOG"
	METRICEXPORTINTEGRATIONTYPE_CLOUDWATCH MetricExportIntegrationType = "CLOUDWATCH"
)

// All allowed values of MetricExportIntegrationType enum.
var AllowedMetricExportIntegrationTypeEnumValues = []MetricExportIntegrationType{
	"DATADOG",
	"CLOUDWATCH",
}

func (v *MetricExportIntegrationType) UnmarshalJSON(src []byte) error {
	var value string
	err := json.Unmarshal(src, &value)
	if err != nil {
		return err
	}
	enumTypeValue := MetricExportIntegrationType(value)
	for _, existing := range AllowedMetricExportIntegrationTypeEnumValues {
		if existing == enumTypeValue {
			*v = enumTypeValue
			return nil
		}
	}

	return fmt.Errorf("%+v is not a valid MetricExportIntegrationType", value)
}

// NewMetricExportIntegrationTypeFromValue returns a pointer to a valid MetricExportIntegrationType
// for the value passed as argument, or an error if the value passed is not allowed by the enum.
func NewMetricExportIntegrationTypeFromValue(v string) (*MetricExportIntegrationType, error) {
	ev := MetricExportIntegrationType(v)
	if ev.IsValid() {
		return &ev, nil
	} else {
		return nil, fmt.Errorf("invalid value '%v' for MetricExportIntegrationType: valid values are %v", v, AllowedMetricExportIntegrationTypeEnumValues)
	}
}

// IsValid return true if the value is valid for the enum, false otherwise.
func (v MetricExportIntegrationType) IsValid() bool {
	for _, existing := range AllowedMetricExportIntegrationTypeEnumValues {
		if existing == v {
			return true
		}
	}
	return false
}

// Ptr returns reference to MetricExportIntegrationType value.
func (v MetricExportIntegrationType) Ptr() *MetricExportIntegrationType {
	return &v
}
