// Copyright 2022 The Cockroach Authors
//
// Licensed under the Apache License, Version 2.0 (the "License");
// you may not use this file except in compliance with the License.
// You may obtain a copy of the License at
//
// 	http://www.apache.org/licenses/LICENSE-2.0
//
// Unless required by applicable law or agreed to in writing, software
// distributed under the License is distributed on an "AS IS" BASIS,
// WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
// See the License for the specific language governing permissions and
// limitations under the License.

// Code generated by OpenAPI Generator (https://openapi-generator.tech); DO NOT EDIT.
// CockroachDB Cloud API
// API version: 2022-03-31

package client

import (
	"encoding/json"
	"fmt"
)

// PageDirection the model 'PageDirection'.
type PageDirection string

// List of PageDirection.
const (
	PAGEDIRECTION_NEXT PageDirection = "PAGE_DIRECTION_NEXT"
	PAGEDIRECTION_LAST PageDirection = "PAGE_DIRECTION_LAST"
)

// All allowed values of PageDirection enum.
var AllowedPageDirectionEnumValues = []PageDirection{
	"PAGE_DIRECTION_NEXT",
	"PAGE_DIRECTION_LAST",
}

func (v *PageDirection) UnmarshalJSON(src []byte) error {
	var value string
	err := json.Unmarshal(src, &value)
	if err != nil {
		return err
	}
	enumTypeValue := PageDirection(value)
	for _, existing := range AllowedPageDirectionEnumValues {
		if existing == enumTypeValue {
			*v = enumTypeValue
			return nil
		}
	}

	return fmt.Errorf("%+v is not a valid PageDirection", value)
}

// NewPageDirectionFromValue returns a pointer to a valid PageDirection
// for the value passed as argument, or an error if the value passed is not allowed by the enum.
func NewPageDirectionFromValue(v string) (*PageDirection, error) {
	ev := PageDirection(v)
	if ev.IsValid() {
		return &ev, nil
	} else {
		return nil, fmt.Errorf("invalid value '%v' for PageDirection: valid values are %v", v, AllowedPageDirectionEnumValues)
	}
}

// IsValid return true if the value is valid for the enum, false otherwise.
func (v PageDirection) IsValid() bool {
	for _, existing := range AllowedPageDirectionEnumValues {
		if existing == v {
			return true
		}
	}
	return false
}

// Ptr returns reference to PageDirection value.
func (v PageDirection) Ptr() *PageDirection {
	return &v
}
