// Code generated by OpenAPI Generator (https://openapi-generator.tech); DO NOT EDIT.
// CockroachDB Cloud API
// API version: 2022-07-12T00:00:00.000Z

package client

import (
	"encoding/json"
	"time"
)

// LogExportClusterInfo LogExportClusterInfo contains a package of information that fully describes both the intended state of the log export configuration for a specific cluster but also some metadata around its deployment status, any error messages, and some timestamps..
type LogExportClusterInfo struct {
	ClusterId            *string                        `json:"cluster_id,omitempty"`
	Status               *LogExportStatus               `json:"status,omitempty"`
	UserMessage          *string                        `json:"user_message,omitempty"`
	Spec                 *LogExportClusterSpecification `json:"spec,omitempty"`
	CreatedAt            *time.Time                     `json:"created_at,omitempty"`
	UpdatedAt            *time.Time                     `json:"updated_at,omitempty"`
	AdditionalProperties map[string]interface{}
}

type logExportClusterInfo LogExportClusterInfo

// NewLogExportClusterInfo instantiates a new LogExportClusterInfo object.
// This constructor will assign default values to properties that have it defined,
// and makes sure properties required by API are set, but the set of arguments
// will change when the set of required properties is changed
func NewLogExportClusterInfo() *LogExportClusterInfo {
	p := LogExportClusterInfo{}
	return &p
}

// GetClusterId returns the ClusterId field value if set, zero value otherwise.
func (o *LogExportClusterInfo) GetClusterId() string {
	if o == nil || o.ClusterId == nil {
		var ret string
		return ret
	}
	return *o.ClusterId
}

// SetClusterId gets a reference to the given string and assigns it to the ClusterId field.
func (o *LogExportClusterInfo) SetClusterId(v string) {
	o.ClusterId = &v
}

// GetStatus returns the Status field value if set, zero value otherwise.
func (o *LogExportClusterInfo) GetStatus() LogExportStatus {
	if o == nil || o.Status == nil {
		var ret LogExportStatus
		return ret
	}
	return *o.Status
}

// SetStatus gets a reference to the given LogExportStatus and assigns it to the Status field.
func (o *LogExportClusterInfo) SetStatus(v LogExportStatus) {
	o.Status = &v
}

// GetUserMessage returns the UserMessage field value if set, zero value otherwise.
func (o *LogExportClusterInfo) GetUserMessage() string {
	if o == nil || o.UserMessage == nil {
		var ret string
		return ret
	}
	return *o.UserMessage
}

// SetUserMessage gets a reference to the given string and assigns it to the UserMessage field.
func (o *LogExportClusterInfo) SetUserMessage(v string) {
	o.UserMessage = &v
}

// GetSpec returns the Spec field value if set, zero value otherwise.
func (o *LogExportClusterInfo) GetSpec() LogExportClusterSpecification {
	if o == nil || o.Spec == nil {
		var ret LogExportClusterSpecification
		return ret
	}
	return *o.Spec
}

// SetSpec gets a reference to the given LogExportClusterSpecification and assigns it to the Spec field.
func (o *LogExportClusterInfo) SetSpec(v LogExportClusterSpecification) {
	o.Spec = &v
}

// GetCreatedAt returns the CreatedAt field value if set, zero value otherwise.
func (o *LogExportClusterInfo) GetCreatedAt() time.Time {
	if o == nil || o.CreatedAt == nil {
		var ret time.Time
		return ret
	}
	return *o.CreatedAt
}

// SetCreatedAt gets a reference to the given time.Time and assigns it to the CreatedAt field.
func (o *LogExportClusterInfo) SetCreatedAt(v time.Time) {
	o.CreatedAt = &v
}

// GetUpdatedAt returns the UpdatedAt field value if set, zero value otherwise.
func (o *LogExportClusterInfo) GetUpdatedAt() time.Time {
	if o == nil || o.UpdatedAt == nil {
		var ret time.Time
		return ret
	}
	return *o.UpdatedAt
}

// SetUpdatedAt gets a reference to the given time.Time and assigns it to the UpdatedAt field.
func (o *LogExportClusterInfo) SetUpdatedAt(v time.Time) {
	o.UpdatedAt = &v
}

func (o LogExportClusterInfo) MarshalJSON() ([]byte, error) {
	toSerialize := map[string]interface{}{}
	if o.ClusterId != nil {
		toSerialize["cluster_id"] = o.ClusterId
	}
	if o.Status != nil {
		toSerialize["status"] = o.Status
	}
	if o.UserMessage != nil {
		toSerialize["user_message"] = o.UserMessage
	}
	if o.Spec != nil {
		toSerialize["spec"] = o.Spec
	}
	if o.CreatedAt != nil {
		toSerialize["created_at"] = o.CreatedAt
	}
	if o.UpdatedAt != nil {
		toSerialize["updated_at"] = o.UpdatedAt
	}

	for key, value := range o.AdditionalProperties {
		toSerialize[key] = value
	}

	return json.Marshal(toSerialize)
}

func (o *LogExportClusterInfo) UnmarshalJSON(bytes []byte) (err error) {
	varLogExportClusterInfo := logExportClusterInfo{}

	if err = json.Unmarshal(bytes, &varLogExportClusterInfo); err == nil {
		*o = LogExportClusterInfo(varLogExportClusterInfo)
	}

	additionalProperties := make(map[string]interface{})

	if err = json.Unmarshal(bytes, &additionalProperties); err == nil {
		delete(additionalProperties, "cluster_id")
		delete(additionalProperties, "status")
		delete(additionalProperties, "user_message")
		delete(additionalProperties, "spec")
		delete(additionalProperties, "created_at")
		delete(additionalProperties, "updated_at")
		o.AdditionalProperties = additionalProperties
	}

	return err
}
