// Code generated by OpenAPI Generator (https://openapi-generator.tech); DO NOT EDIT.
// CockroachDB Cloud API
// API version: 2022-03-31

package client

import (
	"encoding/json"
	"fmt"
)

// ClusterStatusType the model 'ClusterStatusType'.
type ClusterStatusType string

// List of ClusterStatusType.
const (
	CLUSTERSTATUSTYPE_UNSPECIFIED                  ClusterStatusType = "CLUSTER_STATUS_UNSPECIFIED"
	CLUSTERSTATUSTYPE_CRDB_MAJOR_UPGRADE_RUNNING   ClusterStatusType = "CLUSTER_STATUS_CRDB_MAJOR_UPGRADE_RUNNING"
	CLUSTERSTATUSTYPE_CRDB_MAJOR_UPGRADE_FAILED    ClusterStatusType = "CLUSTER_STATUS_CRDB_MAJOR_UPGRADE_FAILED"
	CLUSTERSTATUSTYPE_CRDB_MAJOR_ROLLBACK_RUNNING  ClusterStatusType = "CLUSTER_STATUS_CRDB_MAJOR_ROLLBACK_RUNNING"
	CLUSTERSTATUSTYPE_CRDB_MAJOR_ROLLBACK_FAILED   ClusterStatusType = "CLUSTER_STATUS_CRDB_MAJOR_ROLLBACK_FAILED"
	CLUSTERSTATUSTYPE_CRDB_PATCH_RUNNING           ClusterStatusType = "CLUSTER_STATUS_CRDB_PATCH_RUNNING"
	CLUSTERSTATUSTYPE_CRDB_PATCH_FAILED            ClusterStatusType = "CLUSTER_STATUS_CRDB_PATCH_FAILED"
	CLUSTERSTATUSTYPE_CRDB_SCALE_RUNNING           ClusterStatusType = "CLUSTER_STATUS_CRDB_SCALE_RUNNING"
	CLUSTERSTATUSTYPE_CRDB_SCALE_FAILED            ClusterStatusType = "CLUSTER_STATUS_CRDB_SCALE_FAILED"
	CLUSTERSTATUSTYPE_MAINTENANCE_RUNNING          ClusterStatusType = "CLUSTER_STATUS_MAINTENANCE_RUNNING"
	CLUSTERSTATUSTYPE_CRDB_INSTANCE_UPDATE_RUNNING ClusterStatusType = "CLUSTER_STATUS_CRDB_INSTANCE_UPDATE_RUNNING"
	CLUSTERSTATUSTYPE_CRDB_INSTANCE_UPDATE_FAILED  ClusterStatusType = "CLUSTER_STATUS_CRDB_INSTANCE_UPDATE_FAILED"
	CLUSTERSTATUSTYPE_CRDB_EDIT_CLUSTER_RUNNING    ClusterStatusType = "CLUSTER_STATUS_CRDB_EDIT_CLUSTER_RUNNING"
	CLUSTERSTATUSTYPE_CRDB_EDIT_CLUSTER_FAILED     ClusterStatusType = "CLUSTER_STATUS_CRDB_EDIT_CLUSTER_FAILED"
	CLUSTERSTATUSTYPE_CRDB_CMEK_OPERATION_RUNNING  ClusterStatusType = "CLUSTER_STATUS_CRDB_CMEK_OPERATION_RUNNING"
	CLUSTERSTATUSTYPE_CRDB_CMEK_OPERATION_FAILED   ClusterStatusType = "CLUSTER_STATUS_CRDB_CMEK_OPERATION_FAILED"
)

// All allowed values of ClusterStatusType enum.
var AllowedClusterStatusTypeEnumValues = []ClusterStatusType{
	"CLUSTER_STATUS_UNSPECIFIED",
	"CLUSTER_STATUS_CRDB_MAJOR_UPGRADE_RUNNING",
	"CLUSTER_STATUS_CRDB_MAJOR_UPGRADE_FAILED",
	"CLUSTER_STATUS_CRDB_MAJOR_ROLLBACK_RUNNING",
	"CLUSTER_STATUS_CRDB_MAJOR_ROLLBACK_FAILED",
	"CLUSTER_STATUS_CRDB_PATCH_RUNNING",
	"CLUSTER_STATUS_CRDB_PATCH_FAILED",
	"CLUSTER_STATUS_CRDB_SCALE_RUNNING",
	"CLUSTER_STATUS_CRDB_SCALE_FAILED",
	"CLUSTER_STATUS_MAINTENANCE_RUNNING",
	"CLUSTER_STATUS_CRDB_INSTANCE_UPDATE_RUNNING",
	"CLUSTER_STATUS_CRDB_INSTANCE_UPDATE_FAILED",
	"CLUSTER_STATUS_CRDB_EDIT_CLUSTER_RUNNING",
	"CLUSTER_STATUS_CRDB_EDIT_CLUSTER_FAILED",
	"CLUSTER_STATUS_CRDB_CMEK_OPERATION_RUNNING",
	"CLUSTER_STATUS_CRDB_CMEK_OPERATION_FAILED",
}

func (v *ClusterStatusType) UnmarshalJSON(src []byte) error {
	var value string
	err := json.Unmarshal(src, &value)
	if err != nil {
		return err
	}
	enumTypeValue := ClusterStatusType(value)
	for _, existing := range AllowedClusterStatusTypeEnumValues {
		if existing == enumTypeValue {
			*v = enumTypeValue
			return nil
		}
	}

	return fmt.Errorf("%+v is not a valid ClusterStatusType", value)
}

// NewClusterStatusTypeFromValue returns a pointer to a valid ClusterStatusType
// for the value passed as argument, or an error if the value passed is not allowed by the enum.
func NewClusterStatusTypeFromValue(v string) (*ClusterStatusType, error) {
	ev := ClusterStatusType(v)
	if ev.IsValid() {
		return &ev, nil
	} else {
		return nil, fmt.Errorf("invalid value '%v' for ClusterStatusType: valid values are %v", v, AllowedClusterStatusTypeEnumValues)
	}
}

// IsValid return true if the value is valid for the enum, false otherwise.
func (v ClusterStatusType) IsValid() bool {
	for _, existing := range AllowedClusterStatusTypeEnumValues {
		if existing == v {
			return true
		}
	}
	return false
}

// Ptr returns reference to ClusterStatusType value.
func (v ClusterStatusType) Ptr() *ClusterStatusType {
	return &v
}
