// Copyright 2022 The Cockroach Authors
//
// Licensed under the Apache License, Version 2.0 (the "License");
// you may not use this file except in compliance with the License.
// You may obtain a copy of the License at
//
// 	http://www.apache.org/licenses/LICENSE-2.0
//
// Unless required by applicable law or agreed to in writing, software
// distributed under the License is distributed on an "AS IS" BASIS,
// WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
// See the License for the specific language governing permissions and
// limitations under the License.

// Code generated by OpenAPI Generator (https://openapi-generator.tech); DO NOT EDIT.
// CockroachDB Cloud API
// API version: 2022-09-20

package client

import (
	"encoding/json"
)

// DatadogConfig struct for DatadogConfig.
type DatadogConfig struct {
	ApiKey *string                   `json:"api_key,omitempty"`
	Site   *DatadogConfigDatadogSite `json:"site,omitempty"`
}

// NewDatadogConfig instantiates a new DatadogConfig object.
// This constructor will assign default values to properties that have it defined,
// and makes sure properties required by API are set, but the set of arguments
// will change when the set of required properties is changed
func NewDatadogConfig() *DatadogConfig {
	p := DatadogConfig{}
	return &p
}

// GetApiKey returns the ApiKey field value if set, zero value otherwise.
func (o *DatadogConfig) GetApiKey() string {
	if o == nil || o.ApiKey == nil {
		var ret string
		return ret
	}
	return *o.ApiKey
}

// SetApiKey gets a reference to the given string and assigns it to the ApiKey field.
func (o *DatadogConfig) SetApiKey(v string) {
	o.ApiKey = &v
}

// GetSite returns the Site field value if set, zero value otherwise.
func (o *DatadogConfig) GetSite() DatadogConfigDatadogSite {
	if o == nil || o.Site == nil {
		var ret DatadogConfigDatadogSite
		return ret
	}
	return *o.Site
}

// SetSite gets a reference to the given DatadogConfigDatadogSite and assigns it to the Site field.
func (o *DatadogConfig) SetSite(v DatadogConfigDatadogSite) {
	o.Site = &v
}

func (o DatadogConfig) MarshalJSON() ([]byte, error) {
	toSerialize := map[string]interface{}{}
	if o.ApiKey != nil {
		toSerialize["api_key"] = o.ApiKey
	}
	if o.Site != nil {
		toSerialize["site"] = o.Site
	}
	return json.Marshal(toSerialize)
}
