// Code generated by OpenAPI Generator (https://openapi-generator.tech); DO NOT EDIT.
// CockroachDB Cloud API
// API version: 2022-03-31

package client

import (
	"encoding/json"
)

// CreateSQLUserRequest struct for CreateSQLUserRequest.
type CreateSQLUserRequest struct {
	User                 SQLUser `json:"user"`
	Password             string  `json:"password"`
	AdditionalProperties map[string]interface{}
}

type createSQLUserRequest CreateSQLUserRequest

// NewCreateSQLUserRequest instantiates a new CreateSQLUserRequest object.
// This constructor will assign default values to properties that have it defined,
// and makes sure properties required by API are set, but the set of arguments
// will change when the set of required properties is changed
func NewCreateSQLUserRequest(user SQLUser, password string) *CreateSQLUserRequest {
	p := CreateSQLUserRequest{}
	p.User = user
	p.Password = password
	return &p
}

// NewCreateSQLUserRequestWithDefaults instantiates a new CreateSQLUserRequest object.
// This constructor will only assign default values to properties that have it defined,
// but it doesn't guarantee that properties required by API are set
func NewCreateSQLUserRequestWithDefaults() *CreateSQLUserRequest {
	p := CreateSQLUserRequest{}
	return &p
}

// GetUser returns the User field value.
func (o *CreateSQLUserRequest) GetUser() SQLUser {
	if o == nil {
		var ret SQLUser
		return ret
	}

	return o.User
}

// SetUser sets field value.
func (o *CreateSQLUserRequest) SetUser(v SQLUser) {
	o.User = v
}

// GetPassword returns the Password field value.
func (o *CreateSQLUserRequest) GetPassword() string {
	if o == nil {
		var ret string
		return ret
	}

	return o.Password
}

// SetPassword sets field value.
func (o *CreateSQLUserRequest) SetPassword(v string) {
	o.Password = v
}

func (o CreateSQLUserRequest) MarshalJSON() ([]byte, error) {
	toSerialize := map[string]interface{}{}
	if true {
		toSerialize["user"] = o.User
	}
	if true {
		toSerialize["password"] = o.Password
	}

	for key, value := range o.AdditionalProperties {
		toSerialize[key] = value
	}

	return json.Marshal(toSerialize)
}

func (o *CreateSQLUserRequest) UnmarshalJSON(bytes []byte) (err error) {
	varCreateSQLUserRequest := createSQLUserRequest{}

	if err = json.Unmarshal(bytes, &varCreateSQLUserRequest); err == nil {
		*o = CreateSQLUserRequest(varCreateSQLUserRequest)
	}

	additionalProperties := make(map[string]interface{})

	if err = json.Unmarshal(bytes, &additionalProperties); err == nil {
		delete(additionalProperties, "user")
		delete(additionalProperties, "password")
		o.AdditionalProperties = additionalProperties
	}

	return err
}
