// Code generated by OpenAPI Generator (https://openapi-generator.tech); DO NOT EDIT.
// CockroachDB Cloud API
// API version: 2022-03-31

package client

import (
	"encoding/json"
)

// ServerlessClusterSpecification struct for ServerlessClusterSpecification.
type ServerlessClusterSpecification struct {
	// Region values should match the cloud provider's zone code. For example, for Oregon, set region_name to \"us-west2\" for GCP and \"us-west-2\" for AWS.
	Regions              []string `json:"regions"`
	SpendLimit           int32    `json:"spend_limit"`
	AdditionalProperties map[string]interface{}
}

type serverlessClusterSpecification ServerlessClusterSpecification

// NewServerlessClusterSpecification instantiates a new ServerlessClusterSpecification object.
// This constructor will assign default values to properties that have it defined,
// and makes sure properties required by API are set, but the set of arguments
// will change when the set of required properties is changed
func NewServerlessClusterSpecification(regions []string, spendLimit int32) *ServerlessClusterSpecification {
	p := ServerlessClusterSpecification{}
	p.Regions = regions
	p.SpendLimit = spendLimit
	return &p
}

// NewServerlessClusterSpecificationWithDefaults instantiates a new ServerlessClusterSpecification object.
// This constructor will only assign default values to properties that have it defined,
// but it doesn't guarantee that properties required by API are set
func NewServerlessClusterSpecificationWithDefaults() *ServerlessClusterSpecification {
	p := ServerlessClusterSpecification{}
	return &p
}

// GetRegions returns the Regions field value.
func (o *ServerlessClusterSpecification) GetRegions() []string {
	if o == nil {
		var ret []string
		return ret
	}

	return o.Regions
}

// SetRegions sets field value.
func (o *ServerlessClusterSpecification) SetRegions(v []string) {
	o.Regions = v
}

// GetSpendLimit returns the SpendLimit field value.
func (o *ServerlessClusterSpecification) GetSpendLimit() int32 {
	if o == nil {
		var ret int32
		return ret
	}

	return o.SpendLimit
}

// SetSpendLimit sets field value.
func (o *ServerlessClusterSpecification) SetSpendLimit(v int32) {
	o.SpendLimit = v
}

func (o ServerlessClusterSpecification) MarshalJSON() ([]byte, error) {
	toSerialize := map[string]interface{}{}
	if true {
		toSerialize["regions"] = o.Regions
	}
	if true {
		toSerialize["spend_limit"] = o.SpendLimit
	}

	for key, value := range o.AdditionalProperties {
		toSerialize[key] = value
	}

	return json.Marshal(toSerialize)
}

func (o *ServerlessClusterSpecification) UnmarshalJSON(bytes []byte) (err error) {
	varServerlessClusterSpecification := serverlessClusterSpecification{}

	if err = json.Unmarshal(bytes, &varServerlessClusterSpecification); err == nil {
		*o = ServerlessClusterSpecification(varServerlessClusterSpecification)
	}

	additionalProperties := make(map[string]interface{})

	if err = json.Unmarshal(bytes, &additionalProperties); err == nil {
		delete(additionalProperties, "regions")
		delete(additionalProperties, "spend_limit")
		o.AdditionalProperties = additionalProperties
	}

	return err
}
