// Copyright 2023 The Cockroach Authors
//
// Licensed under the Apache License, Version 2.0 (the "License");
// you may not use this file except in compliance with the License.
// You may obtain a copy of the License at
//
// 	http://www.apache.org/licenses/LICENSE-2.0
//
// Unless required by applicable law or agreed to in writing, software
// distributed under the License is distributed on an "AS IS" BASIS,
// WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
// See the License for the specific language governing permissions and
// limitations under the License.

// Code generated by OpenAPI Generator (https://openapi-generator.tech); DO NOT EDIT.
// CockroachDB Cloud API
// API version: 2023-04-10

package client

import (
	"time"
)

// ReplicationStream struct for ReplicationStream.
type ReplicationStream struct {
	// created_at is the timestamp at which the replication stream was created.
	CreatedAt time.Time `json:"created_at"`
	// cutover describes whether or not cutover has been triggered.
	Cutover bool `json:"cutover"`
	// cutover_at is the timestamp at which cutover occurs. If the user sets `cutover` to `true` but omits cutover_at, the cutover time will default to the latest consistent replicated time. Otherwise, the user can pick a time in the future to schedule a cutover in the future, or a time in the past to restore the cluster to a recent state.
	CutoverAt time.Time `json:"cutover_at"`
	// id is the UUID of the replication stream.
	Id string `json:"id"`
	// source_cluster_id is the ID of the cluster that is being replicated.
	SourceClusterId string                      `json:"source_cluster_id"`
	Status          ReplicationStreamStatusType `json:"status"`
	// target_cluster_id is the ID of the cluster that data is being replicated to.
	TargetClusterId string `json:"target_cluster_id"`
}

// NewReplicationStream instantiates a new ReplicationStream object.
// This constructor will assign default values to properties that have it defined,
// and makes sure properties required by API are set, but the set of arguments
// will change when the set of required properties is changed
func NewReplicationStream(createdAt time.Time, cutover bool, cutoverAt time.Time, id string, sourceClusterId string, status ReplicationStreamStatusType, targetClusterId string) *ReplicationStream {
	p := ReplicationStream{}
	p.CreatedAt = createdAt
	p.Cutover = cutover
	p.CutoverAt = cutoverAt
	p.Id = id
	p.SourceClusterId = sourceClusterId
	p.Status = status
	p.TargetClusterId = targetClusterId
	return &p
}

// NewReplicationStreamWithDefaults instantiates a new ReplicationStream object.
// This constructor will only assign default values to properties that have it defined,
// but it doesn't guarantee that properties required by API are set
func NewReplicationStreamWithDefaults() *ReplicationStream {
	p := ReplicationStream{}
	return &p
}

// GetCreatedAt returns the CreatedAt field value.
func (o *ReplicationStream) GetCreatedAt() time.Time {
	if o == nil {
		var ret time.Time
		return ret
	}

	return o.CreatedAt
}

// SetCreatedAt sets field value.
func (o *ReplicationStream) SetCreatedAt(v time.Time) {
	o.CreatedAt = v
}

// GetCutover returns the Cutover field value.
func (o *ReplicationStream) GetCutover() bool {
	if o == nil {
		var ret bool
		return ret
	}

	return o.Cutover
}

// SetCutover sets field value.
func (o *ReplicationStream) SetCutover(v bool) {
	o.Cutover = v
}

// GetCutoverAt returns the CutoverAt field value.
func (o *ReplicationStream) GetCutoverAt() time.Time {
	if o == nil {
		var ret time.Time
		return ret
	}

	return o.CutoverAt
}

// SetCutoverAt sets field value.
func (o *ReplicationStream) SetCutoverAt(v time.Time) {
	o.CutoverAt = v
}

// GetId returns the Id field value.
func (o *ReplicationStream) GetId() string {
	if o == nil {
		var ret string
		return ret
	}

	return o.Id
}

// SetId sets field value.
func (o *ReplicationStream) SetId(v string) {
	o.Id = v
}

// GetSourceClusterId returns the SourceClusterId field value.
func (o *ReplicationStream) GetSourceClusterId() string {
	if o == nil {
		var ret string
		return ret
	}

	return o.SourceClusterId
}

// SetSourceClusterId sets field value.
func (o *ReplicationStream) SetSourceClusterId(v string) {
	o.SourceClusterId = v
}

// GetStatus returns the Status field value.
func (o *ReplicationStream) GetStatus() ReplicationStreamStatusType {
	if o == nil {
		var ret ReplicationStreamStatusType
		return ret
	}

	return o.Status
}

// SetStatus sets field value.
func (o *ReplicationStream) SetStatus(v ReplicationStreamStatusType) {
	o.Status = v
}

// GetTargetClusterId returns the TargetClusterId field value.
func (o *ReplicationStream) GetTargetClusterId() string {
	if o == nil {
		var ret string
		return ret
	}

	return o.TargetClusterId
}

// SetTargetClusterId sets field value.
func (o *ReplicationStream) SetTargetClusterId(v string) {
	o.TargetClusterId = v
}
