// Copyright 2023 The Cockroach Authors
//
// Licensed under the Apache License, Version 2.0 (the "License");
// you may not use this file except in compliance with the License.
// You may obtain a copy of the License at
//
// 	http://www.apache.org/licenses/LICENSE-2.0
//
// Unless required by applicable law or agreed to in writing, software
// distributed under the License is distributed on an "AS IS" BASIS,
// WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
// See the License for the specific language governing permissions and
// limitations under the License.

// Code generated by OpenAPI Generator (https://openapi-generator.tech); DO NOT EDIT.
// CockroachDB Cloud API
// API version: 2023-04-10

package client

import (
	"encoding/json"
)

// Nullable is used in cases where null is a valid field value.
// To omit the field from the API request, the Nullable object itself
// should be nil. To include the field in the request, but explicitly
// set it to null (i.e. clear the field), set inner to nil.
type Nullable[T any] struct {
	inner *T
}

func (t Nullable[T]) MarshalJSON() ([]byte, error) {
	return json.Marshal(t.inner)
}

func (t Nullable[T]) UnmarshalJSON(in []byte) error {
	return json.Unmarshal(in, t.inner)
}

func (t Nullable[T]) GetValue() T {
	if t.inner == nil {
		var n T
		return n
	}
	return *(t.inner)
}
