name: Changelog Check

on:
  pull_request:
    branches:
      - main
      - 'pending-deploy-*'

jobs:
  changelog:
    uses: cockroachdb/actions/.github/workflows/pr-changelog-check.yml@add-changelog-workflow
    with:
      base-ref: ${{ github.event.pull_request.base.ref }}
      pr-number: ${{ github.event.pull_request.number }}
