name: Create Release PR

on:
  pull_request:
    types: [closed]
    branches:
      - main
  workflow_dispatch:

permissions:
  contents: write
  pull-requests: write

jobs:
  create-release-pr:
    # Run on merged PRs with pending-deploy- prefix, or manual workflow_dispatch
    if: github.event_name == 'workflow_dispatch' || (github.event.pull_request.merged && startsWith(github.event.pull_request.head.ref, 'pending-deploy-'))
    uses: cockroachdb/actions/.github/workflows/create-release-pr.yml@v0
    with:
      fork_owner: FORK_OWNER #TODO(linhcrl): replace
      fork_repo: cockroach-cloud-sdk-go
      build_script: internal/update_version.sh
      files_to_commit: |
        go.mod
        internal/spec/config.yaml
        README.md
        docs/README.md
        pkg/client/configuration.go
    secrets:
      fork_push_token: ${{ secrets.FORK_PUSH_TOKEN }}
      pr_create_token: ${{ secrets.GITHUB_TOKEN }}